spring:
  config:
    activate:
      on-profile: prod
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
    config:
      retry:
        initial-interval: 10000
        max-attempts: 20
        max-interval: 15000
        multiplier: 1.1
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK